version: "3.7"

services:
  angular-forms-front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    command: >
      bash -c "
          npm install
          npm run start"
networks:
  default:
      name: angular-forms-front-network
      external: true
